# Generated by Django 5.0.6 on 2024-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desig', models.CharField(max_length=100)),
                ('para', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='Media/StudentPic')),
            ],
        ),
    ]
