# Generated by Django 5.0.6 on 2024-08-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_studentreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentReview',
            new_name='Student',
        ),
    ]
