# Generated by Django 5.0.6 on 2024-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_studentreview_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='desig',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
